[package]
name = "libpci"
version = "0.1.0"
edition = "2021"
authors = ["Vladislav Nepogodin <nepogodin.vlad@gmail.com>"]
license = "GPLv3"

description = "Rust bindings for libpci"
homepage = "https://github.com/RebornOS-Developers/mhwd-rebornos"
repository = "https://github.com/RebornOS-Developers/mhwd-rebornos"
categories = ["api-bindings"]

[dependencies]
libpci-sys = { path = "../libpci-sys", default-features = false, version = "0.1.0" }
libc = { default-features = false, version = "0.2.142" }

[features]
default = []

std = ["libpci-sys/std"]

[[example]]
name = "example1"
